modLoader = "javafml"
loaderVersion = "[37,)"
license = "All rights reserved"

[[mods]]
modId = "item_predicate_tutorial"
version = "${file.jarVersion}"
displayName = "Item Predicate Tutorial"




[[dependencies.item_predicate_tutorial]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.item_predicate_tutorial]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,1.18)"
ordering = "NONE"
side = "BOTH"
